[build-system]
requires = ["uv_build>=0.11.28,<0.13"]
build-backend = "uv_build"

[project]
name = "anime-cursors"
version = "1.0.0"
description = "Animeted Cursors on Linux"
readme = "README.md"
requires-python = ">=3.14"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
keywords = ["cur", "ani", "x11", "windows", "win32", "cursor", "xcursor"]
authors = [{ name = "ashuramaruzxc", email = "ashuramaru@tenjin-dk.com" }]
maintainers = [{ name = "ashuramaruzxc", email = "ashuramaru@tenjin-dk.com" }]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Win32 (MS Windows)",
  "Environment :: X11 Applications",
  "Intended Audience :: End Users/Desktop",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.14",
  "Topic :: Desktop Environment",
]
dependencies = [
    "cursorgen>=0.1.3",
    "msgspec>=0.22.0",
    "numpy>=2.4",
    "pillow>=12.3",
    "platformdirs>=4.12.3",
    "rich>=15.0.0",
]

[dependency-groups]
dev = ["ruff>=0.16.10", "ty>=0.0.84", "pre-commit>=4.6.2"]

[project.urls]
"Homepage" = "https://github.com/ashuramaruzxc/anime-cursors"
"Bug Reports" = "https://github.com/ashuramaruzxc/anime-cursors/issues"
"Source" = "https://github.com/ashuramaruzxc/anime-cursors"

[project.scripts]
CursorConverter = "CursorConverter.__main__:main"

[tool.uv.build-backend]
module-name = "CursorConverter"
module-root = ""

[tool.ruff]
line-length = 120
target-version = "py314"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]
